name: Validate

on:
  pull_request:
    branches:
      - develop
      - master
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hacs/action@main"
        with:
          category: "integration"
